import {
    MarketForexAudcadIcon,
    MarketForexAudchfIcon,
    MarketForexAudjpyIcon,
    MarketForexAudnzdIcon,
    MarketForexAudusdIcon,
    MarketDerivedAudBasketIcon,
    MarketDerivedBearIcon,
    MarketDerivedBoom1000Icon,
    MarketDerivedBoom600Icon,
    MarketDerivedBoom900Icon,
    MarketDerivedBoom300Icon,
    MarketDerivedBoom500Icon,
    MarketDerivedBullIcon,
    MarketDerivedCrash1000Icon,
    MarketDerivedCrash600Icon,
    MarketDerivedCrash900Icon,
    MarketDerivedCrash300Icon,
    MarketDerivedCrash500Icon,
    MarketCommoditySilverusdIcon,
    MarketCommodityGoldusdIcon,
    MarketCommodityPalladiumusdIcon,
    MarketCommodityPlatinumusdIcon,
    MarketCryptocurrencyBtcusdIcon,
    MarketCryptocurrencyEthusdIcon,
    MarketDerivedEurBasketIcon,
    MarketDerivedGbpBasketIcon,
    MarketDerivedGoldBasketIcon,
    MarketDerivedJump10Icon,
    MarketDerivedJump100Icon,
    MarketDerivedJump25Icon,
    MarketDerivedJump50Icon,
    MarketDerivedJump75Icon,
    MarketDerivedStepIndices100Icon,
    MarketDerivedStepIndices200Icon,
    MarketDerivedStepIndices300Icon,
    MarketDerivedStepIndices400Icon,
    MarketDerivedStepIndices500Icon,
    MarketDerivedUsdBasketIcon,
    MarketDerivedVolatility101sIcon,
    MarketDerivedVolatility1001sIcon,
    MarketDerivedVolatility1501sIcon,
    MarketDerivedVolatility2501sIcon,
    MarketDerivedVolatility251sIcon,
    MarketDerivedVolatility501sIcon,
    MarketDerivedVolatility751sIcon,
    MarketForexEuraudIcon,
    MarketForexEurcadIcon,
    MarketForexEurchfIcon,
    MarketForexEurgbpIcon,
    MarketForexEurjpyIcon,
    MarketForexEurnzdIcon,
    MarketForexEurusdIcon,
    MarketForexGbpaudIcon,
    MarketForexGbpcadIcon,
    MarketForexGbpchfIcon,
    MarketForexGbpjpyIcon,
    MarketForexGbpnokIcon,
    MarketForexGbpnzdIcon,
    MarketForexGbpusdIcon,
    MarketForexNzdjpnIcon,
    MarketForexNzdusdIcon,
    MarketForexUsdcadIcon,
    MarketForexUsdchfIcon,
    MarketForexUsdjpyIcon,
    MarketForexUsdmxnIcon,
    MarketForexUsdnokIcon,
    MarketForexUsdplnIcon,
    MarketForexUsdsekIcon,
    MarketIndicesAustralia200Icon,
    MarketIndicesEuro50Icon,
    MarketIndicesFrance40Icon,
    MarketIndicesGerman40Icon,
    MarketIndicesHongKong50Icon,
    MarketIndicesJapan225Icon,
    MarketIndicesNetherlands25Icon,
    MarketIndicesSwiss20Icon,
    MarketIndicesUk100Icon,
    MarketIndicesUs500Icon,
    MarketIndicesUsTech100Icon,
    MarketIndicesWallStreet30Icon,
    MarketDerivedVolatility10Icon,
    MarketDerivedVolatility100Icon,
    MarketDerivedVolatility25Icon,
    MarketDerivedVolatility50Icon,
    MarketDerivedVolatility75Icon,
    // Additional Forex pairs
    MarketForexAudsgdIcon,
    MarketForexCadchfIcon,
    MarketForexCadjpyIcon,
    MarketForexChfjpyIcon,
    MarketForexEurhkdIcon,
    MarketForexEurilsIcon,
    MarketForexEurmxnIcon,
    MarketForexEurnokIcon,
    MarketForexEurplnIcon,
    MarketForexEursekIcon,
    MarketForexEursgdIcon,
    MarketForexEurzarIcon,
    MarketForexGbpsekIcon,
    MarketForexGbpsgdIcon,
    MarketForexHkdjpyIcon,
    MarketForexNzdcadIcon,
    MarketForexNzdchfIcon,
    MarketForexNzdsgdIcon,
    MarketForexSgdjpyIcon,
    MarketForexUsdcnhIcon,
    MarketForexUsdhkdIcon,
    MarketForexUsdilsIcon,
    MarketForexUsdrubIcon,
    MarketForexUsdsgdIcon,
    MarketForexUsdthbIcon,
    MarketForexUsdzarIcon,
    // Additional Indices
    MarketIndicesChina50Icon,
    MarketIndicesChinaHSharesIcon,
    MarketIndicesSingapore20Icon,
    MarketIndicesSpain35Icon,
    MarketIndicesTaiwanIndexIcon,
    // Additional Commodities
    MarketCommodityAluminiumusdIcon,
    MarketCommodityCopperusdIcon,
    MarketCommodityGoldeurIcon,
    MarketCommodityLeadusdIcon,
    MarketCommodityNickelusdIcon,
    MarketCommoditySilvereurIcon,
    MarketCommodityZincusdIcon,
    // Energy
    MarketEnergyBrentCrudeOilukIcon,
    MarketEnergyNgasIcon,
    MarketEnergyWtiOilusIcon,
    // Metals
    MarketMetalAluminiumIcon,
    MarketMetalCopperIcon,
    MarketMetalGoldIcon,
    MarketMetalLeadIcon,
    MarketMetalNickelIcon,
    MarketMetalPalladiumIcon,
    MarketMetalPlatinumIcon,
    MarketMetalSilverIcon,
    MarketMetalZincIcon,
    // Soft Commodities
    MarketSoftCommodityCocoaIcon,
    MarketSoftCommodityCoffeeArabicaIcon,
    MarketSoftCommodityCoffeeRobustaIcon,
    MarketSoftCommodityCottonIcon,
    MarketSoftCommoditySugarIcon,
    // Additional Cryptocurrencies
    MarketCryptocurrencyAdausdIcon,
    MarketCryptocurrencyAlgusdIcon,
    MarketCryptocurrencyAvausdIcon,
    MarketCryptocurrencyBatusdIcon,
    MarketCryptocurrencyBchusdIcon,
    MarketCryptocurrencyBnbusdIcon,
    MarketCryptocurrencyBtcethIcon,
    MarketCryptocurrencyBtcltcIcon,
    MarketCryptocurrencyDogusdIcon,
    MarketCryptocurrencyDotusdIcon,
    MarketCryptocurrencyDshusdIcon,
    MarketCryptocurrencyEosusdIcon,
    MarketCryptocurrencyEtcusdIcon,
    MarketCryptocurrencyFilusdIcon,
    MarketCryptocurrencyIotusdIcon,
    MarketCryptocurrencyLtcusdIcon,
    MarketCryptocurrencyMkrusdIcon,
    MarketCryptocurrencyMtcusdIcon,
    MarketCryptocurrencyNeousdIcon,
    MarketCryptocurrencyOmgusdIcon,
    MarketCryptocurrencySolusdIcon,
    MarketCryptocurrencyTrxusdIcon,
    MarketCryptocurrencyUniusdIcon,
    MarketCryptocurrencyXlmusdIcon,
    MarketCryptocurrencyXmrusdIcon,
    MarketCryptocurrencyXrpusdIcon,
    MarketCryptocurrencyXtzusdIcon,
    MarketCryptocurrencyZecusdIcon,
    // Additional Derived Markets
    MarketDerivedAudusdDfx10Icon,
    MarketDerivedAudusdDfx20Icon,
    MarketDerivedDex1500dnIcon,
    MarketDerivedDex1500upIcon,
    MarketDerivedDex600dnIcon,
    MarketDerivedDex600upIcon,
    MarketDerivedDex900dnIcon,
    MarketDerivedDex900upIcon,
    MarketDerivedDsi10mIcon,
    MarketDerivedDsi20mIcon,
    MarketDerivedDsi30mIcon,
    MarketDerivedEurusdDfx10Icon,
    MarketDerivedEurusdDfx20Icon,
    MarketDerivedGbpusdDfx10Icon,
    MarketDerivedGbpusdDfx20Icon,
    MarketDerivedJump150Icon,
    MarketDerivedJump200Icon,
    MarketDerivedRangeBreak100Icon,
    MarketDerivedRangeBreak200Icon,
    MarketDerivedSkewStepIndex4DownIcon,
    MarketDerivedSkewStepIndex4UpIcon,
    MarketDerivedSkewStepIndex5DownIcon,
    MarketDerivedSkewStepIndex5UpIcon,
    MarketDerivedStepIcon,
    MarketDerivedUsdchfDfx10Icon,
    MarketDerivedUsdchfDfx20Icon,
    MarketDerivedUsdjpyDfx10Icon,
    MarketDerivedUsdjpyDfx20Icon,
    MarketDerivedVolatility901sIcon,
    MarketDerivedVolatilityOverBoom400Icon,
    MarketDerivedVolatilityOverBoom550Icon,
    MarketDerivedVolatilityOverBoom750Icon,
    MarketDerivedVolatilityOverCrash400Icon,
    MarketDerivedVolatilityOverCrash550Icon,
    MarketDerivedVolatilityOverCrash750Icon,
    // Tactical Indices
    MarketTacticalIndicesSilverPullbackIcon,
    MarketTacticalIndicesSilverReboundIcon,
    MarketTacticalIndicesSilverTrendDownIcon,
    MarketTacticalIndicesSilverTrendUpIcon,
    // US Indices
    MarketUsMidcap400Icon,
    MarketUsSmallcap2000Icon,
    // Stocks
    MarketStocksAdidasSalomonIcon,
    MarketStocksAdvancedMicroDevicesIcon,
    MarketStocksAirFranceIcon,
    MarketStocksAirbnbIcon,
    MarketStocksAirbusIcon,
    MarketStocksAlibabaIcon,
    MarketStocksAlphabetIcon,
    MarketStocksAmazonIcon,
    MarketStocksAmcIcon,
    MarketStocksAmericanAirlinesIcon,
    MarketStocksAmericanInternationalGroupIcon,
    MarketStocksAppleIcon,
    MarketStocksBankOfAmericaIcon,
    MarketStocksBayerIcon,
    MarketStocksBeyondMeatIcon,
    MarketStocksBiogenIcon,
    MarketStocksBlackberryIcon,
    MarketStocksBmwIcon,
    MarketStocksBoeingIcon,
    MarketStocksCiscoIcon,
    MarketStocksCitigroupIcon,
    MarketStocksCocacolaIcon,
    MarketStocksCoinbaseIcon,
    MarketStocksContinentalIcon,
    MarketStocksDeltaAirLinesIcon,
    MarketStocksDeutscheBankIcon,
    MarketStocksDeutscheLufthansaIcon,
    MarketStocksEbayIcon,
    MarketStocksFedexIcon,
    MarketStocksFoxIcon,
    MarketStocksGameStopIcon,
    MarketStocksGeneralMotorsIcon,
    MarketStocksGoldmanSacsIcon,
    MarketStocksHomeDepotIcon,
    MarketStocksHpIcon,
    MarketStocksHugoBossIcon,
    MarketStocksIbmIcon,
    MarketStocksIntelIcon,
    MarketStocksJohnsonAndJohnsonIcon,
    MarketStocksJpMorganChaseIcon,
    MarketStocksMastercardIcon,
    MarketStocksMcdonaldsIcon,
    MarketStocksMetaIcon,
    MarketStocksMicroStrategyIcon,
    MarketStocksMicronIcon,
    MarketStocksMicrosoftIcon,
    MarketStocksModernaIcon,
    MarketStocksNestleIcon,
    MarketStocksNetflixIcon,
    MarketStocksNikeIcon,
    MarketStocksNokiaIcon,
    MarketStocksNovartisIcon,
    MarketStocksNvidiaIcon,
    MarketStocksPalantirTechnologiesIcon,
    MarketStocksPaypalIcon,
    MarketStocksPepsicoIcon,
    MarketStocksPerformanceShippingIncIcon,
    MarketStocksPfizerIcon,
    MarketStocksPorscheIcon,
    MarketStocksProcterAndGambleIcon,
    MarketStocksPumaIcon,
    MarketStocksRivianIcon,
    MarketStocksSalesforceIcon,
    MarketStocksSonyIcon,
    MarketStocksSupermicroIcon,
    MarketStocksTeslaIcon,
    MarketStocksTevaIcon,
    MarketStocksTwitterIcon,
    MarketStocksUberIcon,
    MarketStocksVirginGalacticIcon,
    MarketStocksVisaIcon,
    MarketStocksWalmartIcon,
    MarketStocksWaltDisneyIcon,
    MarketStocksZoomIcon,
} from '@deriv/quill-icons';
import type { IconTypes } from '@deriv/quill-icons';

export const marketIcons: {
    [key: string]: IconTypes;
} = {
    frxAUDCAD: MarketForexAudcadIcon,
    frxAUDCHF: MarketForexAudchfIcon,
    frxAUDJPY: MarketForexAudjpyIcon,
    frxAUDNZD: MarketForexAudnzdIcon,
    frxAUDUSD: MarketForexAudusdIcon,
    WLDAUD: MarketDerivedAudBasketIcon,
    RDBEAR: MarketDerivedBearIcon,
    BOOM1000: MarketDerivedBoom1000Icon,
    BOOM600: MarketDerivedBoom600Icon,
    BOOM900: MarketDerivedBoom900Icon,
    BOOM300N: MarketDerivedBoom300Icon,
    BOOM500: MarketDerivedBoom500Icon,
    RDBULL: MarketDerivedBullIcon,
    CRASH1000: MarketDerivedCrash1000Icon,
    CRASH600: MarketDerivedCrash600Icon,
    CRASH900: MarketDerivedCrash900Icon,
    CRASH300N: MarketDerivedCrash300Icon,
    CRASH500: MarketDerivedCrash500Icon,
    frxXAGUSD: MarketCommoditySilverusdIcon,
    frxXAUUSD: MarketCommodityGoldusdIcon,
    frxXPDUSD: MarketCommodityPalladiumusdIcon,
    frxXPTUSD: MarketCommodityPlatinumusdIcon,
    cryBTCUSD: MarketCryptocurrencyBtcusdIcon,
    cryETHUSD: MarketCryptocurrencyEthusdIcon,
    WLDEUR: MarketDerivedEurBasketIcon,
    WLDGBP: MarketDerivedGbpBasketIcon,
    WLDXAU: MarketDerivedGoldBasketIcon,
    JD10: MarketDerivedJump10Icon,
    JD100: MarketDerivedJump100Icon,
    JD25: MarketDerivedJump25Icon,
    JD50: MarketDerivedJump50Icon,
    JD75: MarketDerivedJump75Icon,
    stpRNG: MarketDerivedStepIndices100Icon,
    stpRNG2: MarketDerivedStepIndices200Icon,
    stpRNG3: MarketDerivedStepIndices300Icon,
    stpRNG4: MarketDerivedStepIndices400Icon,
    stpRNG5: MarketDerivedStepIndices500Icon,
    WLDUSD: MarketDerivedUsdBasketIcon,
    '1HZ10V': MarketDerivedVolatility101sIcon,
    '1HZ100V': MarketDerivedVolatility1001sIcon,
    '1HZ150V': MarketDerivedVolatility1501sIcon,
    '1HZ250V': MarketDerivedVolatility2501sIcon,
    '1HZ25V': MarketDerivedVolatility251sIcon,
    '1HZ50V': MarketDerivedVolatility501sIcon,
    '1HZ75V': MarketDerivedVolatility751sIcon,
    frxEURAUD: MarketForexEuraudIcon,
    frxEURCAD: MarketForexEurcadIcon,
    frxEURCHF: MarketForexEurchfIcon,
    frxEURGBP: MarketForexEurgbpIcon,
    frxEURJPY: MarketForexEurjpyIcon,
    frxEURNZD: MarketForexEurnzdIcon,
    frxEURUSD: MarketForexEurusdIcon,
    frxGBPAUD: MarketForexGbpaudIcon,
    frxGBPCAD: MarketForexGbpcadIcon,
    frxGBPCHF: MarketForexGbpchfIcon,
    frxGBPJPY: MarketForexGbpjpyIcon,
    frxGBPNOK: MarketForexGbpnokIcon,
    frxGBPNZD: MarketForexGbpnzdIcon,
    frxGBPUSD: MarketForexGbpusdIcon,
    frxNZDJPY: MarketForexNzdjpnIcon,
    frxNZDUSD: MarketForexNzdusdIcon,
    frxUSDCAD: MarketForexUsdcadIcon,
    frxUSDCHF: MarketForexUsdchfIcon,
    frxUSDJPY: MarketForexUsdjpyIcon,
    frxUSDMXN: MarketForexUsdmxnIcon,
    frxUSDNOK: MarketForexUsdnokIcon,
    frxUSDPLN: MarketForexUsdplnIcon,
    frxUSDSEK: MarketForexUsdsekIcon,
    OTC_AS51: MarketIndicesAustralia200Icon,
    OTC_SX5E: MarketIndicesEuro50Icon,
    OTC_FCHI: MarketIndicesFrance40Icon,
    OTC_GDAXI: MarketIndicesGerman40Icon,
    OTC_HSI: MarketIndicesHongKong50Icon,
    OTC_N225: MarketIndicesJapan225Icon,
    OTC_AEX: MarketIndicesNetherlands25Icon,
    OTC_SSMI: MarketIndicesSwiss20Icon,
    OTC_FTSE: MarketIndicesUk100Icon,
    OTC_SPC: MarketIndicesUs500Icon,
    OTC_NDX: MarketIndicesUsTech100Icon,
    OTC_DJI: MarketIndicesWallStreet30Icon,
    R_10: MarketDerivedVolatility10Icon,
    R_100: MarketDerivedVolatility100Icon,
    R_25: MarketDerivedVolatility25Icon,
    R_50: MarketDerivedVolatility50Icon,
    R_75: MarketDerivedVolatility75Icon,
    R_35: MarketDerivedVolatility25Icon,
    R_90: MarketDerivedVolatility100Icon,
    // Additional Forex pairs
    frxAUDSGD: MarketForexAudsgdIcon,
    frxCADCHF: MarketForexCadchfIcon,
    frxCADJPY: MarketForexCadjpyIcon,
    frxCHFJPY: MarketForexChfjpyIcon,
    frxEURHKD: MarketForexEurhkdIcon,
    frxEURILS: MarketForexEurilsIcon,
    frxEURMXN: MarketForexEurmxnIcon,
    frxEURNOK: MarketForexEurnokIcon,
    frxEURPLN: MarketForexEurplnIcon,
    frxEURSEK: MarketForexEursekIcon,
    frxEURSGD: MarketForexEursgdIcon,
    frxEURZAR: MarketForexEurzarIcon,
    frxGBPSEK: MarketForexGbpsekIcon,
    frxGBPSGD: MarketForexGbpsgdIcon,
    frxHKDJPY: MarketForexHkdjpyIcon,
    frxNZDCAD: MarketForexNzdcadIcon,
    frxNZDCHF: MarketForexNzdchfIcon,
    frxNZDSGD: MarketForexNzdsgdIcon,
    frxSGDJPY: MarketForexSgdjpyIcon,
    frxUSDCNH: MarketForexUsdcnhIcon,
    frxUSDHKD: MarketForexUsdhkdIcon,
    frxUSDILS: MarketForexUsdilsIcon,
    frxUSDRUB: MarketForexUsdrubIcon,
    frxUSDSGD: MarketForexUsdsgdIcon,
    frxUSDTHB: MarketForexUsdthbIcon,
    frxUSDZAR: MarketForexUsdzarIcon,
    // Additional Indices
    OTC_CHN50: MarketIndicesChina50Icon,
    OTC_CHNHS: MarketIndicesChinaHSharesIcon,
    OTC_SIN20: MarketIndicesSingapore20Icon,
    OTC_ES35: MarketIndicesSpain35Icon,
    OTC_TWII: MarketIndicesTaiwanIndexIcon,
    // Additional Commodities
    frxALUMUSD: MarketCommodityAluminiumusdIcon,
    frxCOPUSD: MarketCommodityCopperusdIcon,
    frxAUDEUR: MarketCommodityGoldeurIcon,
    frxLEADUSD: MarketCommodityLeadusdIcon,
    frxNICKUSD: MarketCommodityNickelusdIcon,
    frxXAGEUR: MarketCommoditySilvereurIcon,
    frxZINCUSD: MarketCommodityZincusdIcon,
    // Energy
    OTC_BRENT: MarketEnergyBrentCrudeOilukIcon,
    OTC_NGAS: MarketEnergyNgasIcon,
    OTC_WTI: MarketEnergyWtiOilusIcon,
    // Metals
    METAL_ALUMINIUM: MarketMetalAluminiumIcon,
    METAL_COPPER: MarketMetalCopperIcon,
    METAL_GOLD: MarketMetalGoldIcon,
    METAL_LEAD: MarketMetalLeadIcon,
    METAL_NICKEL: MarketMetalNickelIcon,
    METAL_PALLADIUM: MarketMetalPalladiumIcon,
    METAL_PLATINUM: MarketMetalPlatinumIcon,
    METAL_SILVER: MarketMetalSilverIcon,
    METAL_ZINC: MarketMetalZincIcon,
    // Soft Commodities
    SOFT_COCOA: MarketSoftCommodityCocoaIcon,
    SOFT_COFFEE_ARABICA: MarketSoftCommodityCoffeeArabicaIcon,
    SOFT_COFFEE_ROBUSTA: MarketSoftCommodityCoffeeRobustaIcon,
    SOFT_COTTON: MarketSoftCommodityCottonIcon,
    SOFT_SUGAR: MarketSoftCommoditySugarIcon,
    // Additional Cryptocurrencies
    cryADAUSD: MarketCryptocurrencyAdausdIcon,
    cryALGUSD: MarketCryptocurrencyAlgusdIcon,
    cryAVAUSD: MarketCryptocurrencyAvausdIcon,
    cryBATUSD: MarketCryptocurrencyBatusdIcon,
    cryBCHUSD: MarketCryptocurrencyBchusdIcon,
    cryBNBUSD: MarketCryptocurrencyBnbusdIcon,
    cryBTCETH: MarketCryptocurrencyBtcethIcon,
    cryBTCLTC: MarketCryptocurrencyBtcltcIcon,
    cryDOGEUSD: MarketCryptocurrencyDogusdIcon,
    cryDOTUSD: MarketCryptocurrencyDotusdIcon,
    cryDSHUSD: MarketCryptocurrencyDshusdIcon,
    cryEOSUSD: MarketCryptocurrencyEosusdIcon,
    cryETCUSD: MarketCryptocurrencyEtcusdIcon,
    cryFILUSD: MarketCryptocurrencyFilusdIcon,
    cryIOTUSD: MarketCryptocurrencyIotusdIcon,
    cryLTCUSD: MarketCryptocurrencyLtcusdIcon,
    cryMKRUSD: MarketCryptocurrencyMkrusdIcon,
    cryMTCUSD: MarketCryptocurrencyMtcusdIcon,
    cryNEOUSD: MarketCryptocurrencyNeousdIcon,
    cryOMGUSD: MarketCryptocurrencyOmgusdIcon,
    crySOLUSD: MarketCryptocurrencySolusdIcon,
    cryTRXUSD: MarketCryptocurrencyTrxusdIcon,
    cryUNIUSD: MarketCryptocurrencyUniusdIcon,
    cryXLMUSD: MarketCryptocurrencyXlmusdIcon,
    cryXMRUSD: MarketCryptocurrencyXmrusdIcon,
    cryXRPUSD: MarketCryptocurrencyXrpusdIcon,
    cryXTZUSD: MarketCryptocurrencyXtzusdIcon,
    cryZECUSD: MarketCryptocurrencyZecusdIcon,
    // Additional Derived Markets
    DFXAUDUSD_10: MarketDerivedAudusdDfx10Icon,
    DFXAUDUSD_20: MarketDerivedAudusdDfx20Icon,
    DEX1500DN: MarketDerivedDex1500dnIcon,
    DEX1500UP: MarketDerivedDex1500upIcon,
    DEX600DN: MarketDerivedDex600dnIcon,
    DEX600UP: MarketDerivedDex600upIcon,
    DEX900DN: MarketDerivedDex900dnIcon,
    DEX900UP: MarketDerivedDex900upIcon,
    DSI10M: MarketDerivedDsi10mIcon,
    DSI20M: MarketDerivedDsi20mIcon,
    DSI30M: MarketDerivedDsi30mIcon,
    DFxEURUSD_10: MarketDerivedEurusdDfx10Icon,
    DFxEURUSD_20: MarketDerivedEurusdDfx20Icon,
    DFXGBPUSD_10: MarketDerivedGbpusdDfx10Icon,
    DFXGBPUSD_20: MarketDerivedGbpusdDfx20Icon,
    JD150: MarketDerivedJump150Icon,
    JD200: MarketDerivedJump200Icon,
    RDBREAK100: MarketDerivedRangeBreak100Icon,
    RDBREAK200: MarketDerivedRangeBreak200Icon,
    SKEW4D: MarketDerivedSkewStepIndex4DownIcon,
    SKEW4U: MarketDerivedSkewStepIndex4UpIcon,
    SKEW5D: MarketDerivedSkewStepIndex5DownIcon,
    SKEW5U: MarketDerivedSkewStepIndex5UpIcon,
    STEP: MarketDerivedStepIcon,
    DFXUSDCHF_10: MarketDerivedUsdchfDfx10Icon,
    DFXUSDCHF_20: MarketDerivedUsdchfDfx20Icon,
    DFXUSDJPY_10: MarketDerivedUsdjpyDfx10Icon,
    DFXUSDJPY_20: MarketDerivedUsdjpyDfx20Icon,
    '1HZ901V': MarketDerivedVolatility901sIcon,
    VOLBOOM400: MarketDerivedVolatilityOverBoom400Icon,
    VOLBOOM550: MarketDerivedVolatilityOverBoom550Icon,
    VOLBOOM750: MarketDerivedVolatilityOverBoom750Icon,
    VOLCRASH400: MarketDerivedVolatilityOverCrash400Icon,
    VOLCRASH550: MarketDerivedVolatilityOverCrash550Icon,
    VOLCRASH750: MarketDerivedVolatilityOverCrash750Icon,
    // Tactical Indices
    SILVER_PULLBACK: MarketTacticalIndicesSilverPullbackIcon,
    SILVER_REBOUND: MarketTacticalIndicesSilverReboundIcon,
    SILVER_TREND_DOWN: MarketTacticalIndicesSilverTrendDownIcon,
    SILVER_TREND_UP: MarketTacticalIndicesSilverTrendUpIcon,
    // US Indices
    USMIDCAP400: MarketUsMidcap400Icon,
    USSMALLCAP2000: MarketUsSmallcap2000Icon,
    // Stocks (using common stock symbols)
    STK_ADIDAS: MarketStocksAdidasSalomonIcon,
    STK_AMD: MarketStocksAdvancedMicroDevicesIcon,
    STK_AIRFRANCE: MarketStocksAirFranceIcon,
    STK_AIRBNB: MarketStocksAirbnbIcon,
    STK_AIRBUS: MarketStocksAirbusIcon,
    STK_ALIBABA: MarketStocksAlibabaIcon,
    STK_ALPHABET: MarketStocksAlphabetIcon,
    STK_AMAZON: MarketStocksAmazonIcon,
    STK_AMC: MarketStocksAmcIcon,
    STK_AMERICAN_AIRLINES: MarketStocksAmericanAirlinesIcon,
    STK_AIG: MarketStocksAmericanInternationalGroupIcon,
    STK_APPLE: MarketStocksAppleIcon,
    STK_BANK_OF_AMERICA: MarketStocksBankOfAmericaIcon,
    STK_BAYER: MarketStocksBayerIcon,
    STK_BEYOND_MEAT: MarketStocksBeyondMeatIcon,
    STK_BIOGEN: MarketStocksBiogenIcon,
    STK_BLACKBERRY: MarketStocksBlackberryIcon,
    STK_BMW: MarketStocksBmwIcon,
    STK_BOEING: MarketStocksBoeingIcon,
    STK_CISCO: MarketStocksCiscoIcon,
    STK_CITIGROUP: MarketStocksCitigroupIcon,
    STK_COCA_COLA: MarketStocksCocacolaIcon,
    STK_COINBASE: MarketStocksCoinbaseIcon,
    STK_CONTINENTAL: MarketStocksContinentalIcon,
    STK_DELTA: MarketStocksDeltaAirLinesIcon,
    STK_DEUTSCHE_BANK: MarketStocksDeutscheBankIcon,
    STK_LUFTHANSA: MarketStocksDeutscheLufthansaIcon,
    STK_EBAY: MarketStocksEbayIcon,
    STK_FEDEX: MarketStocksFedexIcon,
    STK_FOX: MarketStocksFoxIcon,
    STK_GAMESTOP: MarketStocksGameStopIcon,
    STK_GM: MarketStocksGeneralMotorsIcon,
    STK_GOLDMAN_SACHS: MarketStocksGoldmanSacsIcon,
    STK_HOME_DEPOT: MarketStocksHomeDepotIcon,
    STK_HP: MarketStocksHpIcon,
    STK_HUGO_BOSS: MarketStocksHugoBossIcon,
    STK_IBM: MarketStocksIbmIcon,
    STK_INTEL: MarketStocksIntelIcon,
    STK_JOHNSON_JOHNSON: MarketStocksJohnsonAndJohnsonIcon,
    STK_JPMORGAN: MarketStocksJpMorganChaseIcon,
    STK_MASTERCARD: MarketStocksMastercardIcon,
    STK_MCDONALDS: MarketStocksMcdonaldsIcon,
    STK_META: MarketStocksMetaIcon,
    STK_MICROSTRATEGY: MarketStocksMicroStrategyIcon,
    STK_MICRON: MarketStocksMicronIcon,
    STK_MICROSOFT: MarketStocksMicrosoftIcon,
    STK_MODERNA: MarketStocksModernaIcon,
    STK_NESTLE: MarketStocksNestleIcon,
    STK_NETFLIX: MarketStocksNetflixIcon,
    STK_NIKE: MarketStocksNikeIcon,
    STK_NOKIA: MarketStocksNokiaIcon,
    STK_NOVARTIS: MarketStocksNovartisIcon,
    STK_NVIDIA: MarketStocksNvidiaIcon,
    STK_PALANTIR: MarketStocksPalantirTechnologiesIcon,
    STK_PAYPAL: MarketStocksPaypalIcon,
    STK_PEPSICO: MarketStocksPepsicoIcon,
    STK_PERFORMANCE_SHIPPING: MarketStocksPerformanceShippingIncIcon,
    STK_PFIZER: MarketStocksPfizerIcon,
    STK_PORSCHE: MarketStocksPorscheIcon,
    STK_P_and_G: MarketStocksProcterAndGambleIcon,
    STK_PUMA: MarketStocksPumaIcon,
    STK_RIVIAN: MarketStocksRivianIcon,
    STK_SALESFORCE: MarketStocksSalesforceIcon,
    STK_SONY: MarketStocksSonyIcon,
    STK_SUPERMICRO: MarketStocksSupermicroIcon,
    STK_TESLA: MarketStocksTeslaIcon,
    STK_TEVA: MarketStocksTevaIcon,
    STK_TWITTER: MarketStocksTwitterIcon,
    STK_UBER: MarketStocksUberIcon,
    STK_VIRGIN_GALACTIC: MarketStocksVirginGalacticIcon,
    STK_VISA: MarketStocksVisaIcon,
    STK_WALMART: MarketStocksWalmartIcon,
    STK_DISNEY: MarketStocksWaltDisneyIcon,
    STK_ZOOM: MarketStocksZoomIcon,
} as const;
